[audio0,fs0] = audioread("John Bovey - Passive Aggressive.wav");


audio0 = audio0(1:2048);

win = sqrt(hann(1024,"periodic"));
overlapLength = floor(numel(win)/2);
fftLength = 2^nextpow2(numel(win) + 1);


ystft = stft(audio0, ...
        "Window",win, ...
        "OverlapLength",overlapLength, ...
        "FFTLength",fftLength, ...
        "Centered",true);
y = istft(ystft, ...
    "Window",win, ...
    "OverlapLength",overlapLength, ...
    "FFTLength",fftLength); 
    %"ConjugateSymmetric",true);
